services:
  db:
    image: postgres:17
    container_name: diabetes_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: 
      context: .
      dockerfile: Dockerfile.fasthtml
    container_name: diabetes_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    # Usamos las mismas variables para construir la URL de conexión
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    command: uvicorn DayBetes_food.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      db:
        condition: service_started


  tailwind:

    build:
      context: .
      dockerfile: Dockerfile.tailwind
    container_name: diabetes_tailwind
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    command: tailwindcss -i DayBetes_food/static/css/input.css -o DayBetes_food/static/css/output.css --watch

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: diabetes_tunnel
    command: tunnel --config /home/nonroot/.cloudflared/config.yml run daybetes
    volumes:
      - ~/.cloudflared:/home/nonroot/.cloudflared
    depends_on:
      web:
        condition: service_started
