# Lightweight Python base image
FROM python:3.12-slim

# Do not write .pyc files and show logs in real time
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Working directory inside the container
WORKDIR /app

# System dependencies needed for PostgreSQL (psycopg)
RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*


# Copy and install the Python libraries
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Port used by FastHTML
EXPOSE 8000